import React, { useEffect, useState } from 'react'
import { usePublicClient } from 'wagmi'
import { parseAbiItem, formatUnits } from 'viem'
import { CONTRACT_ADDRESS } from '../config'
import jsPDF from 'jspdf'

const eventItem = parseAbiItem('event PayrollPaid(address indexed wallet, uint256 amount, uint256 timestamp, bytes32 txRef)')

export default function History() {
  const client = usePublicClient()
  const [fromDate, setFromDate] = useState<string>('') // datetime-local value
  const [toDate, setToDate] = useState<string>('')     // datetime-local value
  const [rows, setRows] = useState<Array<{ wallet: string, amount: string, timestamp: number, txHash: string, txRef?: string, blockNumber?: number }>>([])
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    let mounted = true
    async function initDefaults() {
      // default to last 30 days
      const now = new Date()
      const past = new Date(now.getTime() - 30 * 24 * 60 * 60 * 1000)
      const to = new Date(now.getTime() - now.getSeconds() * 1000) // strip seconds for nicer input
      const fmt = (d: Date) => {
        const pad = (n: number) => n.toString().padStart(2, '0')
        return `${d.getFullYear()}-${pad(d.getMonth() + 1)}-${pad(d.getDate())}T${pad(d.getHours())}:${pad(d.getMinutes())}`
      }
      if (!mounted) return
      setFromDate(fmt(past))
      setToDate(fmt(to))
    }
    if (client) initDefaults()
    return () => { mounted = false }
  }, [client])

  const load = async () => {
    if (!client) return
    setLoading(true)
    try {
      // Determine approximate block window from selected date range
      const latestBlock = Number(await client.getBlockNumber())
      const nowSec = Math.floor(Date.now() / 1000)
      const fromSec = fromDate ? Math.floor(new Date(fromDate).getTime() / 1000) : nowSec - 30 * 24 * 60 * 60
      const toSec = toDate ? Math.floor(new Date(toDate).getTime() / 1000) : nowSec
      const rangeSec = Math.max(0, toSec - fromSec)
      // Assume ~5s block time on Celo Alfajores; clamp range to keep RPC happy
      const approxBlocks = Math.min(500_000, Math.max(50_000, Math.ceil(rangeSec / 5) + 10_000))
      const fromBlock = BigInt(Math.max(0, latestBlock - approxBlocks))
      const toBlock = BigInt(latestBlock)

      const logs = await client.getLogs({
        address: CONTRACT_ADDRESS as `0x${string}`,
        events: [eventItem],
        fromBlock,
        toBlock,
      })
      const parsedAll = logs.map((l) => ({
        wallet: (l.args as any).wallet as string,
        amount: formatUnits((l.args as any).amount as bigint, 18),
        timestamp: Number((l.args as any).timestamp),
        txHash: l.transactionHash,
        txRef: ((l.args as any).txRef as string) ?? undefined,
        blockNumber: l.blockNumber ? Number(l.blockNumber) : undefined,
      })).reverse()
      // Filter by selected date range using the event timestamp
      const filtered = parsedAll.filter(r => {
        return r.timestamp >= fromSec && r.timestamp <= toSec
      })
      setRows(filtered)
    } catch (e) {
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => { if (fromDate && toDate) { load() } }, [fromDate, toDate])

  const downloadReceipt = (r: { wallet: string, amount: string, timestamp: number, txHash: string, txRef?: string, blockNumber?: number }) => {
    const doc = new jsPDF()
    let y = 20
    doc.setFontSize(16)
    doc.text('Payroll Payment Receipt', 14, y)
    y += 10
    doc.setFontSize(11)
    const lines: Array<[string, string]> = [
      ['Contract', CONTRACT_ADDRESS],
      ['Network', 'Celo Alfajores (44787)'],
      ['Employee Wallet', r.wallet],
      ['Amount', `${r.amount} cUSD`],
      ['Timestamp (UTC)', new Date(r.timestamp * 1000).toUTCString()],
      ['Transaction Hash', r.txHash],
    ]
    if (r.txRef) lines.push(['Tx Ref', r.txRef])
    if (r.blockNumber) lines.push(['Block', String(r.blockNumber)])
    lines.forEach(([k, v]) => {
      doc.text(`${k}:`, 14, y)
      doc.text(String(v), 60, y)
      y += 8
    })
    doc.setFontSize(9)
    doc.text('Generated by Payroll dApp', 14, y + 4)
    const short = r.txHash.slice(0, 10)
    doc.save(`receipt_${short}.pdf`)
  }

  return (
    <div className="card">
      <div className="section-title">Payroll History</div>
      <div className="grid md:grid-cols-3 gap-3 mb-3">
        <div>
          <div className="label">From (UTC)</div>
          <input className="input" type="datetime-local" value={fromDate} onChange={e => setFromDate(e.target.value)} />
        </div>
        <div>
          <div className="label">To (UTC)</div>
          <input className="input" type="datetime-local" value={toDate} onChange={e => setToDate(e.target.value)} />
        </div>
        <div className="flex items-end">
          <button className="btn btn-outline" onClick={load} disabled={loading}>{loading ? 'Loading…' : 'Refresh'}</button>
        </div>
      </div>

      <div className="overflow-x-auto">
        <table className="w-full text-sm">
          <thead className="text-gray-300">
            <tr>
              <th className="text-left p-2">Wallet</th>
              <th className="text-left p-2">Amount (cUSD)</th>
              <th className="text-left p-2">Timestamp</th>
              <th className="text-left p-2">Tx</th>
              <th className="text-left p-2">Receipt</th>
            </tr>
          </thead>
          <tbody>
            {rows.map((r, idx) => (
              <tr key={idx} className="border-t border-[#1b2741]">
                <td className="p-2 break-all">{r.wallet}</td>
                <td className="p-2">{r.amount}</td>
                <td className="p-2">{new Date(r.timestamp * 1000).toLocaleString()}</td>
                <td className="p-2 break-all">{r.txHash}</td>
                <td className="p-2"><button className="btn btn-outline" onClick={() => downloadReceipt(r)}>Download</button></td>
              </tr>
            ))}
            {!rows.length && !loading && (
              <tr><td className="p-2" colSpan={5}>No events in selected range.</td></tr>
            )}
          </tbody>
        </table>
      </div>
    </div>
  )
}
